added templates
moja-global/contributor-website-v2 pull request #13
Opened 2021-06-01 06:47 UTC by rutujaingole

wrt issue no. #3. Added the Issue Templates and PR template.

2021-06-09 07:24 UTC, sarthakkundra requested changes

2021-06-09 07:24 UTC, sarthakkundra commented on website/.github/PULL_REQUEST_TEMPLATE.md
> +Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.
Remove `which issue is fixed`

2021-06-09 07:24 UTC, sarthakkundra commented on website/.github/PULL_REQUEST_TEMPLATE.md
> +- [ ] I have commented my code, particularly in hard-to-understand areas
remove

2021-06-09 07:24 UTC, sarthakkundra commented on website/.github/PULL_REQUEST_TEMPLATE.md
> +- [ ] My changes generate no new warnings
remove

2021-06-09 07:24 UTC, sarthakkundra commented on website/.github/PULL_REQUEST_TEMPLATE.md
> +- [ ] I have added tests that prove my fix is effective or that my feature works
Change to `I have added corresponding tests`.

2021-06-09 07:24 UTC, sarthakkundra commented on website/.github/PULL_REQUEST_TEMPLATE.md
> +- [ ] New and existing unit tests pass locally with my changes
remove

2021-06-09 07:24 UTC, sarthakkundra commented on website/.github/PULL_REQUEST_TEMPLATE.md
> +- [ ] I have checked my code and corrected any misspellings
remove

2021-06-09 07:24 UTC, sarthakkundra commented on website/.github/PULL_REQUEST_TEMPLATE.md
> +- [ ] I have tagged the reviewers in a comment below incase my pull request is ready for a review
remove

2021-06-09 07:24 UTC, sarthakkundra commented on website/.github/ISSUE_TEMPLATE/user-feedback.md
> +---
What will be the use case of this? I can see this potentially overlapping with the feature request or bug report

2021-06-09 07:24 UTC, sarthakkundra commented on website/.github/ISSUE_TEMPLATE/science-contribution-and-review-.md
> +---
What is the use case of this?

2021-06-09 07:24 UTC, sarthakkundra commented on website/.github/ISSUE_TEMPLATE/communication-suggestion.md
> +---
Can see this potentially overlapping with feature request or bug report so remove this.

2021-06-09 08:11 UTC, rutujaingole commented
@sarthakkundra made all the requested changes. Let me know if any further changes are required!

2021-06-12 04:47 UTC, HarshCasper commented
Hi @rutujaingole 

Can you fix the DCO? 

You can do the same by running: 

```
$ git rebase HEAD~11 --signoff
$ git push --force-with-lease origin
```

If possible please squash your commits as well using rebase operation.

2021-06-12 08:23 UTC, rutujaingole commented
@sarthakkundra  I've made the changes. Please review them and let me know if any further changes are to be made!

2021-06-15 10:29 UTC, HarshCasper approved these changes

2021-06-23 07:45 UTC, merged